# The blog configuration 

name: mxdws
description: Learning to design in the front end
author: Martin
permalink: /blog/:title/

email: me@domain.com
twitter: mxdws

# This is the default that's used to preview.
# Change this to your website's URL when you publish your site.
url: https://mxdws.github.io/espresso
